// Visit the wiki for more info - https://kubejs.com/
RecipeViewerEvents.removeRecipes(event => {
    event.remove('minecraft:crafter'),
    event.remove('aquaculture:neptunium_helmet'),
    event.remove('aquaculture:neptunium_chestplate'),
    event.remove('aquaculture:neptunium_leggings'),
    event.remove('aquaculture:neptunium_boots')
    event.remove('aquaculture:neptunium_pickaxe')
    event.remove('aquaculture:neptunium_axe')
    event.remove('aquaculture:neptunium_shovel')
    event.remove('aquaculture:neptunium_sword')
    event.remove('aquaculture:neptunium_bow')  
    event.remove('aquaculture:neptunium_hoe')  
    event.remove('redstonepen:remote') 
    event.remove('redstonepen:basic_gauge')
    event.remove('minecraft:spyglass')
    event.remove('mctb:yellow_bioshroom_crafting_table')
    event.remove('mctb:ru_willow_crafting_table')
    event.remove('mctb:socotra_crafting_table')
    event.remove('mctb:ru_redwood_crafting_table')
    event.remove('mctb:pink_bioshroom_crafting_table')
    event.remove('mctb:pine_crafting_table')
    event.remove('mctb:ru_palm_crafting_table')
    event.remove('mctb:mauve_crafting_table')
    event.remove('mctb:maple_crafting_table')
    event.remove('mctb:magnolia_crafting_table')
    event.remove('mctb:larch_crafting_table')
    event.remove('mctb:kapok_crafting_table')
    event.remove('mctb:joshua_crafting_table')
    event.remove('mctb:green_bioshroom_crafting_table')
    event.remove('mctb:eucalyptus_crafting_table')
    event.remove('mctb:ru_dead_crafting_table')
    event.remove('mctb:cypress_crafting_table')
    event.remove('mctb:cobalt_crafting_table')
    event.remove('mctb:brimwood_crafting_table')
    event.remove('mctb:blue_bioshroom_crafting_table')
    event.remove('mctb:blackwood_crafting_table')
    event.remove('mctb:baobab_crafting_table')
    event.remove('mctb:alpha_crafting_table')
	event.remove('mctb:towerwood_crafting_table')
    event.remove('mctb:sorting_crafting_table')
    event.remove('mctb:mining_crafting_table')
    event.remove('mctb:transformation_crafting_table')
    event.remove('mctb:time_crafting_table')
    event.remove('mctb:dark_crafting_table')
    event.remove('mctb:twilight_mangrove_crafting_table')
    event.remove('mctb:canopy_crafting_table')
    event.remove('mctb:twilight_oak_crafting_table')
    event.remove('mctb:grongle_crafting_table')
    event.remove('mctb:wigglewood_crafting_table')
    event.remove('mctb:smogstem_crafting_table')
    event.remove('mctb:ad_ancient_crafting_table')
    event.remove('mctb:glacian_crafting_table')
    event.remove('mctb:strophar_crafting_table')
    event.remove('mctb:aeronos_crafting_table')
    event.remove('mctb:ancient_crafting_table')
    event.remove('mctb:azalea_crafting_table')
    event.remove('mctb:empyreal_crafting_table')
    event.remove('mctb:hellbark_crafting_table')
    event.remove('mctb:umbran_crafting_table')
	event.remove('mctb:magic_crafting_table')
    event.remove('mctb:dead_crafting_table')
    event.remove('mctb:willow_crafting_table')
    event.remove('mctb:palm_crafting_table')
    event.remove('mctb:jacaranda_crafting_table')
    event.remove('mctb:mahogany_crafting_table')
    event.remove('mctb:redwood_crafting_table')
    event.remove('mctb:bop_maple_crafting_table')
    event.remove('mctb:bop_pine_crafting_table')
    event.remove('mctb:fir_crafting_table')
})

ServerEvents.recipes(event => {
    event.remove({output: 'minecraft:crafter'}),
    event.remove({output: 'aquaculture:neptunium_helmet'}),
    event.remove({output: 'aquaculture:neptunium_chestplate'}),
    event.remove({output: 'aquaculture:neptunium_leggings'}),
    event.remove({output: 'aquaculture:neptunium_boots'})
    event.remove({output: 'aquaculture:neptunium_pickaxe'})
    event.remove({output: 'aquaculture:neptunium_axe'})
    event.remove({output: 'aquaculture:neptunium_shovel'})
    event.remove({output: 'aquaculture:neptunium_sword'})
    event.remove({output: 'aquaculture:neptunium_bow'})
    event.remove({output: 'aquaculture:neptunium_hoe'})
    event.remove({output: 'redstonepen:remote'})
    event.remove({output: 'redstonepen:basic_gauge'})
    event.remove({output: 'minecraft:spyglass'})
    event.remove({output: 'mctb:yellow_bioshroom_crafting_table'})
    event.remove({output: 'mctb:ru_willow_crafting_table'})
    event.remove({output: 'mctb:socotra_crafting_table'})
    event.remove({output: 'mctb:ru_redwood_crafting_table'})
	event.remove({output: 'mctb:pink_bioshroom_crafting_table'})
	event.remove({output: 'mctb:pine_crafting_table'})
    event.remove({output: 'mctb:ru_palm_crafting_table'})
    event.remove({output: 'mctb:mauve_crafting_table'})
    event.remove({output: 'mctb:maple_crafting_table'})
    event.remove({output: 'mctb:magnolia_crafting_table'})
    event.remove({output: 'mctb:larch_crafting_table'})
    event.remove({output: 'mctb:kapok_crafting_table'})
    event.remove({output: 'mctb:joshua_crafting_table'})
    event.remove({output: 'mctb:green_bioshroom_crafting_table'})
    event.remove({output: 'mctb:eucalyptus_crafting_table'})
    event.remove({output: 'mctb:ru_dead_crafting_table'})
    event.remove({output: 'mctb:cypress_crafting_table'})
    event.remove({output: 'mctb:cobalt_crafting_table'})
    event.remove({output: 'mctb:brimwood_crafting_table'})
    event.remove({output: 'mctb:blue_bioshroom_crafting_table'})
    event.remove({output: 'mctb:blackwood_crafting_table'})
    event.remove({output: 'mctb:baobab_crafting_table'})
    event.remove({output: 'mctb:alpha_crafting_table'})
	event.remove({output: 'mctb:towerwood_crafting_table'})
    event.remove({output: 'mctb:sorting_crafting_table'})
    event.remove({output: 'mctb:mining_crafting_table'})
    event.remove({output: 'mctb:transformation_crafting_table'})
    event.remove({output: 'mctb:time_crafting_table'})
    event.remove({output: 'mctb:dark_crafting_table'})
    event.remove({output: 'mctb:twilight_mangrove_crafting_table'})
    event.remove({output: 'mctb:canopy_crafting_table'})
    event.remove({output: 'mctb:twilight_oak_crafting_table'})
    event.remove({output: 'mctb:grongle_crafting_table'})
    event.remove({output: 'mctb:wigglewood_crafting_table'})
    event.remove({output: 'mctb:smogstem_crafting_table'})
    event.remove({output: 'mctb:ad_ancient_crafting_table'})
    event.remove({output: 'mctb:glacian_crafting_table'})
    event.remove({output: 'mctb:strophar_crafting_table'})
    event.remove({output: 'mctb:aeronos_crafting_table'})
    event.remove({output: 'mctb:ancient_crafting_table'})
    event.remove({output: 'mctb:azalea_crafting_table'})
    event.remove({output: 'mctb:empyreal_crafting_table'})
    event.remove({output: 'mctb:hellbark_crafting_table'})
    event.remove({output: 'mctb:umbran_crafting_table'})
	event.remove({output: 'mctb:magic_crafting_table'})
    event.remove({output: 'mctb:dead_crafting_table'})
    event.remove({output: 'mctb:willow_crafting_table'})
    event.remove({output: 'mctb:palm_crafting_table'})
    event.remove({output: 'mctb:jacaranda_crafting_table'})
    event.remove({output: 'mctb:mahogany_crafting_table'})
    event.remove({output: 'mctb:redwood_crafting_table'})
    event.remove({output: 'mctb:bop_maple_crafting_table'})
    event.remove({output: 'mctb:bop_pine_crafting_table'})
    event.remove({output: 'mctb:fir_crafting_table'})
})


ServerEvents.tags("worldgen/biome", (event) => {
    event.get("ae2:has_meteorites").removeAll()
  })