! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! terralith:lavender_forest > aurorasdeco:lavender_plains
! terralith:lavender_valley > aurorasdeco:lavender_plains
! terralith:cave/infested_caves > minecraft:dripstone_caves
! 
! For full biome list, see https://minecraft.wiki/w/Biome#Biome_IDs

incendium:toxic_heap > null
incendium:quartz_flats > null
incendium:infernal_dunes > null
incendium:volcanic_deltas > null
incendium:weeping_valley > null
incendium:withered_forest > null
incendium:inverted_forest > null