#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Wed Jan 29 16:56:02 EET 2025
a=false
chipped=true
farmersdelight=true
handcrafted=true
mctb=true
mcwbridges=true
mcwdoors=true
mcwfences=true
mcwfurnitures=true
mcwlights=true
mcwpaths=true
mcwroofs=true
mcwstairs=true
mcwtrpdoors=true
mcwwindows=true
refurbished_furniture=true
