#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Sun Jan 26 19:16:20 EET 2025
a=false
another_furniture=true
chipped=true
farmersdelight=true
handcrafted=true
mctb=true
mcwbridges=true
mcwdoors=true
mcwfences=true
mcwfurnitures=true
mcwlights=true
mcwpaths=true
mcwroofs=true
mcwstairs=true
mcwtrpdoors=true
mcwwindows=true
valhelsia_furniture=true
