#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Mon Mar 10 18:01:15 EET 2025
a=false
another_furniture=true
chipped=true
create=true
farmersdelight=true
handcrafted=true
mctb=true
mcwwindows=true
refurbished_furniture=true
