#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jan 26 19:38:50 EET 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.3.zip
