#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jan 29 16:56:09 EET 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.4 + EuphoriaPatches_1.5.1.zip
