#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 16 21:09:41 EEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.9.3 + EuphoriaPatches_1.10.5
